// Generated by Dagger (https://google.github.io/dagger).
package ca.llamabagel.transpo.di;

import dagger.internal.Factory;
import dagger.internal.Preconditions;
import retrofit2.Converter;

public final class CoreModule_ProvideSerializationConverterFactoryFactory
    implements Factory<Converter.Factory> {
  private final CoreModule module;

  public CoreModule_ProvideSerializationConverterFactoryFactory(CoreModule module) {
    this.module = module;
  }

  @Override
  public Converter.Factory get() {
    return proxyProvideSerializationConverterFactory(module);
  }

  public static CoreModule_ProvideSerializationConverterFactoryFactory create(CoreModule module) {
    return new CoreModule_ProvideSerializationConverterFactoryFactory(module);
  }

  public static Converter.Factory proxyProvideSerializationConverterFactory(CoreModule instance) {
    return Preconditions.checkNotNull(
        instance.provideSerializationConverterFactory(),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
