// Generated by Dagger (https://google.github.io/dagger).
package ca.llamabagel.transpo.di;

import com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

public final class CoreModule_ProvideCallAdapterFactoryFactory
    implements Factory<CoroutineCallAdapterFactory> {
  private final CoreModule module;

  public CoreModule_ProvideCallAdapterFactoryFactory(CoreModule module) {
    this.module = module;
  }

  @Override
  public CoroutineCallAdapterFactory get() {
    return proxyProvideCallAdapterFactory(module);
  }

  public static CoreModule_ProvideCallAdapterFactoryFactory create(CoreModule module) {
    return new CoreModule_ProvideCallAdapterFactoryFactory(module);
  }

  public static CoroutineCallAdapterFactory proxyProvideCallAdapterFactory(CoreModule instance) {
    return Preconditions.checkNotNull(
        instance.provideCallAdapterFactory(),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
