// Generated by Dagger (https://google.github.io/dagger).
package ca.llamabagel.transpo.di;

import android.content.SharedPreferences;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

public final class SharedPreferencesModule_ProvideSharedPreferencesFactory
    implements Factory<SharedPreferences> {
  private final SharedPreferencesModule module;

  public SharedPreferencesModule_ProvideSharedPreferencesFactory(SharedPreferencesModule module) {
    this.module = module;
  }

  @Override
  public SharedPreferences get() {
    return proxyProvideSharedPreferences(module);
  }

  public static SharedPreferencesModule_ProvideSharedPreferencesFactory create(
      SharedPreferencesModule module) {
    return new SharedPreferencesModule_ProvideSharedPreferencesFactory(module);
  }

  public static SharedPreferences proxyProvideSharedPreferences(SharedPreferencesModule instance) {
    return Preconditions.checkNotNull(
        instance.provideSharedPreferences(),
        "Cannot return null from a non-@Nullable @Provides method");
  }
}
